# Generated by Django 5.0 on 2024-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100)),
                ('form_details', models.TextField()),
                ('formtype', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(max_length=150)),
                ('TimeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
