# Generated by Django 5.0 on 2024-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('guiders', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('city', models.CharField(max_length=300)),
                ('from_details', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='userform_photos/')),
                ('pdf_files', models.FileField(blank=True, null=True, upload_to='userform_pdfs/')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
