# Generated by Django 5.0 on 2024-01-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0002_userform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='from_details',
            new_name='from_name',
        ),
    ]
