# Generated by Django 5.0 on 2024-01-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0004_rename_from_name_userform_form_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='pdf_files',
        ),
        migrations.AlterField(
            model_name='userform',
            name='photos',
            field=models.ImageField(upload_to=''),
        ),
    ]
