# Generated by Django 5.0 on 2024-01-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0006_remove_userform_photos_userformimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userform',
            new_name='Formfill',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
