# Generated by Django 5.0 on 2024-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogtype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
