# Generated by Django 4.2.3 on 2023-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
    ]
